"""Configuration for validator"""

import os

# Output directories
VALIDATION_OUTPUT_DIR = "./validation_results"
VALIDATION_SCRIPTS_DIR = "./validation_scripts"

# Validation thresholds
TRUTH_TABLE_CONFIDENCE_THRESHOLD = 0.8
LLM_VERIFIER_CONFIDENCE_THRESHOLD = 0.8
DATASET_REUSE_CONFIDENCE = 0.75

# LLM settings
LLM_TEMPERATURE = 0.2
LLM_MAX_RETRIES = 3

# RAG settings
RAG_TOP_K = 3
RAG_TOP_K_CHUNKS = 3
RAG_MIN_CHUNK_LENGTH = 50
RAG_MAX_CHUNK_LENGTH = 500
RAG_SIMILARITY_THRESHOLD = 0.3

# Script execution
SCRIPT_TIMEOUT = 60
SCRIPT_TIMEOUT_SECONDS = 30
SCRIPT_MAX_OUTPUT_LENGTH = 10000

# API keys
GOOGLE_FACT_CHECK_API_KEY = os.getenv('GOOGLE_FACT_CHECK_API_KEY', '')

