/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Launch a new run. Provide either a multipart PDF upload (``pdf``) or
         *     the server-local path to an existing PDF (``pdf_path``, e.g. under pdfs/).
         */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pdfs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pdfs */
        get: operations["list_pdfs_api_pdfs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Delete Run */
        delete: operations["delete_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/login-complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Complete
         * @description Unblocks FileInteractionHandler.await_login (§8) for a paused run.
         */
        post: operations["login_complete_api_runs__run_id__login_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Runs */
        get: operations["compare_runs_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Claims */
        get: operations["list_claims_api_runs__run_id__claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Claim */
        get: operations["get_claim_api_runs__run_id__claims__claim_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_runs__run_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/sources/{citation_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Citation */
        post: operations["retry_citation_api_runs__run_id__sources__citation_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/paper.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Pdf */
        get: operations["get_paper_pdf_api_runs__run_id__paper_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/highlights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Highlights */
        get: operations["get_highlights_api_runs__run_id__highlights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchRef */
        BatchRef: {
            /** Citation Id */
            citation_id: string;
            /** Download Successful */
            download_successful: boolean;
            /** Winning Url */
            winning_url?: string | null;
            /** Format */
            format?: string | null;
            /** Resolution Attempts */
            resolution_attempts?: components["schemas"]["ResolutionAttempt"][];
            /** Notes */
            notes: string;
            /** Sibling Claim Ids */
            sibling_claim_ids?: string[];
        };
        /** Body_create_run_api_runs_post */
        Body_create_run_api_runs_post: {
            /** Pdf */
            pdf?: string | null;
            /** Pdf Path */
            pdf_path?: string | null;
        };
        /**
         * CitationDetails
         * @description Details about a citation
         */
        CitationDetails: {
            /** Title */
            title?: string | null;
            /** Authors */
            authors?: string[] | null;
            /** Year */
            year?: number | null;
            /** Url */
            url?: string | null;
            /** Doi */
            doi?: string | null;
            /** Raw Text */
            raw_text: string;
        };
        /** CitationRef */
        CitationRef: {
            /** Id */
            id?: string | null;
            /** Marker */
            marker?: string | null;
            /** Raw Text */
            raw_text?: string | null;
            details?: components["schemas"]["CitationDetails"] | null;
        };
        /**
         * ClaimDetail
         * @description ClaimRow plus the extras only the detail drawer (S4) needs.
         */
        ClaimDetail: {
            /** Claim Id */
            claim_id: string;
            /** Text */
            text: string;
            /** Claim Type */
            claim_type: string;
            /**
             * Group
             * @enum {string}
             */
            group: "qual_uncited" | "quant_uncited" | "qual_cited" | "quant_cited";
            /** Is Original */
            is_original: boolean;
            /** Originally Uncited */
            originally_uncited: boolean;
            found_source?: components["schemas"]["FoundDatasetSource"] | null;
            citation?: components["schemas"]["CitationRef"] | null;
            location_in_text?: components["schemas"]["LocationRef"] | null;
            result?: components["schemas"]["ResultRef"] | null;
            batch?: components["schemas"]["BatchRef"] | null;
            /** Generated Script Path */
            generated_script_path?: string | null;
            /** Raw Citation Text */
            raw_citation_text?: string | null;
            /** Generated Script Source */
            generated_script_source?: string | null;
            /** Sibling Claims */
            sibling_claims?: components["schemas"]["ClaimRow"][];
        };
        /** ClaimRow */
        ClaimRow: {
            /** Claim Id */
            claim_id: string;
            /** Text */
            text: string;
            /** Claim Type */
            claim_type: string;
            /**
             * Group
             * @enum {string}
             */
            group: "qual_uncited" | "quant_uncited" | "qual_cited" | "quant_cited";
            /** Is Original */
            is_original: boolean;
            /** Originally Uncited */
            originally_uncited: boolean;
            found_source?: components["schemas"]["FoundDatasetSource"] | null;
            citation?: components["schemas"]["CitationRef"] | null;
            location_in_text?: components["schemas"]["LocationRef"] | null;
            result?: components["schemas"]["ResultRef"] | null;
            batch?: components["schemas"]["BatchRef"] | null;
            /** Generated Script Path */
            generated_script_path?: string | null;
        };
        /** ClaimsPage */
        ClaimsPage: {
            /** Claims */
            claims: components["schemas"]["ClaimRow"][];
            /** Total */
            total: number;
            /** Facets */
            facets?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** CompareResult */
        CompareResult: {
            /** Run A */
            run_a: string;
            /** Run B */
            run_b: string;
            /** Rows */
            rows: components["schemas"]["CompareRow"][];
        };
        /** CompareRow */
        CompareRow: {
            /** Claim Id */
            claim_id: string;
            /** Text */
            text: string;
            /** A Verdict */
            a_verdict?: ("passed" | "failed" | "unresolved_source" | "skipped") | null;
            /** A Confidence */
            a_confidence?: number | null;
            /** B Verdict */
            b_verdict?: ("passed" | "failed" | "unresolved_source" | "skipped") | null;
            /** B Confidence */
            b_confidence?: number | null;
            /**
             * Changed
             * @default false
             */
            changed: boolean;
        };
        /** ConfigStatus */
        ConfigStatus: {
            /** Env Keys */
            env_keys: {
                [key: string]: boolean;
            };
            /** Thresholds */
            thresholds: {
                [key: string]: unknown;
            };
        };
        /** CostSummary */
        CostSummary: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Input Cost
             * @default 0
             */
            input_cost: number;
            /**
             * Output Cost
             * @default 0
             */
            output_cost: number;
            /**
             * Total Cost
             * @default 0
             */
            total_cost: number;
        };
        /**
         * FoundDatasetSource
         * @description Dataset source found by sourcefinder for originally uncited claims
         */
        FoundDatasetSource: {
            /** Source Url */
            source_url: string;
            /** Source Type */
            source_type: string;
            /** Relevance Score */
            relevance_score: number;
            /** Found By Claim Id */
            found_by_claim_id: string;
            /**
             * Reused Count
             * @default 0
             */
            reused_count: number;
            /** Search Query */
            search_query?: string | null;
            /** Found At */
            found_at?: string;
        };
        /** FunnelStage */
        FunnelStage: {
            /** Stage */
            stage: string;
            /** Count */
            count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HighlightQuad */
        HighlightQuad: {
            /** Claim Id */
            claim_id: string;
            /** Page */
            page: number;
            /** Quads */
            quads: number[][];
        };
        /** LocationRef */
        LocationRef: {
            /** Start */
            start?: number | null;
            /** End */
            end?: number | null;
            /** Chunk Id */
            chunk_id?: number | null;
        };
        /**
         * ResolutionAttempt
         * @description One URL try when resolving a citation to a downloadable source.
         */
        ResolutionAttempt: {
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Downloaded */
            downloaded: boolean;
            /** Error */
            error?: string | null;
        };
        /** ResultRef */
        ResultRef: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "passed" | "failed" | "unresolved_source" | "skipped";
            /** Passed */
            passed: boolean;
            /** Confidence */
            confidence: number;
            /** Method */
            method: string;
            /** Explanation */
            explanation: string;
            /** Errors */
            errors?: string | null;
            /** Sources Used */
            sources_used?: string[];
            /** Validated At */
            validated_at?: string | null;
            /** Validation Metadata */
            validation_metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** RetryRequest */
        RetryRequest: {
            /** Override Url */
            override_url?: string | null;
        };
        /** RetryResponse */
        RetryResponse: {
            /** Citation Id */
            citation_id: string;
            /** Download Successful */
            download_successful: boolean;
            /** Num Claims */
            num_claims: number;
            /** Job Id */
            job_id: string;
        };
        /** RunCreateResponse */
        RunCreateResponse: {
            /** Run Id */
            run_id: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Run Id */
            run_id: string;
            /** Pdf Stem */
            pdf_stem: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "awaiting_login" | "complete" | "failed";
            /** Total Elapsed Seconds */
            total_elapsed_seconds?: number | null;
            cost?: components["schemas"]["CostSummary"] | null;
            /** Steps */
            steps?: {
                [key: string]: components["schemas"]["StepStats"];
            };
            /** Verdict Breakdown */
            verdict_breakdown?: components["schemas"]["VerdictBreakdown"][];
            /** Resolution Funnel */
            resolution_funnel?: components["schemas"]["FunnelStage"][];
            /** Awaiting Login Domains */
            awaiting_login_domains?: string[];
        };
        /** RunSummaryRow */
        RunSummaryRow: {
            /** Run Id */
            run_id: string;
            /** Pdf Stem */
            pdf_stem: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "awaiting_login" | "complete" | "failed";
            /** Total Claims */
            total_claims?: number | null;
            /** Passed */
            passed?: number | null;
            /** Failed */
            failed?: number | null;
            /** Unresolved Source */
            unresolved_source?: number | null;
            /** Pass Rate */
            pass_rate?: number | null;
            /** Unresolved Source Rate */
            unresolved_source_rate?: number | null;
            /** Total Elapsed Seconds */
            total_elapsed_seconds?: number | null;
            cost?: components["schemas"]["CostSummary"] | null;
            /** Awaiting Login Domains */
            awaiting_login_domains?: string[];
        };
        /** SourceRow */
        SourceRow: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "dataset" | "text";
            /** Citation Id */
            citation_id: string;
            /** Citation Text */
            citation_text?: string | null;
            /** Raw Citation Text */
            raw_citation_text?: string | null;
            citation_details?: components["schemas"]["CitationDetails"] | null;
            /** Resolution Attempts */
            resolution_attempts?: components["schemas"]["ResolutionAttempt"][];
            /** Winning Url */
            winning_url?: string | null;
            /** Format */
            format?: string | null;
            /** Filename */
            filename?: string | null;
            /** Downloaded At */
            downloaded_at?: string | null;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Batch Num Claims
             * @default 0
             */
            batch_num_claims: number;
            /**
             * Batch Download Successful
             * @default false
             */
            batch_download_successful: boolean;
        };
        /** StepStats */
        StepStats: {
            /** Elapsed Seconds */
            elapsed_seconds?: number | null;
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Avg Confidence */
            avg_confidence?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerdictBreakdown */
        VerdictBreakdown: {
            /**
             * Group
             * @enum {string}
             */
            group: "qual_uncited" | "quant_uncited" | "qual_cited" | "quant_cited";
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Unresolved Source
             * @default 0
             */
            unresolved_source: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryRow"][];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_run_api_runs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pdfs_api_pdfs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_complete_api_runs__run_id__login_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_runs_api_compare_get: {
        parameters: {
            query: {
                a: string;
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_claims_api_runs__run_id__claims_get: {
        parameters: {
            query?: {
                group?: string | null;
                verdict?: string | null;
                claim_type?: string | null;
                method?: string | null;
                citation_id?: string | null;
                is_original?: boolean | null;
                originally_uncited?: boolean | null;
                min_confidence?: number | null;
                max_confidence?: number | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_claim_api_runs__run_id__claims__claim_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_runs__run_id__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_citation_api_runs__run_id__sources__citation_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                citation_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_pdf_api_runs__run_id__paper_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_highlights_api_runs__run_id__highlights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighlightQuad"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigStatus"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
