/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Launch a new run. Provide either a multipart PDF upload (``pdf``) or
         *     the server-local path to an existing PDF (``pdf_path``, e.g. under pdfs/).
         */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pdfs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pdfs */
        get: operations["list_pdfs_api_pdfs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Delete Run */
        delete: operations["delete_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List References
         * @description Tier 0.6 bibliography audit: every reference in the paper, whether it was
         *     found in the free indexes, and whether it has been retracted.
         *
         *     Empty for runs made before the audit existed.
         */
        get: operations["list_references_api_runs__run_id__references_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/login-complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Complete
         * @description Unblocks FileInteractionHandler.await_login (§8) for a paused run.
         */
        post: operations["login_complete_api_runs__run_id__login_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Runs */
        get: operations["compare_runs_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Claims */
        get: operations["list_claims_api_runs__run_id__claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Claim */
        get: operations["get_claim_api_runs__run_id__claims__claim_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_runs__run_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/sources/{citation_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Citation */
        post: operations["retry_citation_api_runs__run_id__sources__citation_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/paper.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Pdf */
        get: operations["get_paper_pdf_api_runs__run_id__paper_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/highlights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Highlights */
        get: operations["get_highlights_api_runs__run_id__highlights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Credentials
         * @description The credential catalogue plus what is currently set.
         *
         *     Secret values are never returned — only presence and a last-four hint.
         */
        get: operations["get_credentials_api_config_credentials_get"];
        /**
         * Put Credentials
         * @description Write credentials to the repo-root ``.env``.
         *
         *     Only names in the catalogue are accepted: this endpoint must not become a
         *     way to set arbitrary environment variables for a subprocess the API then
         *     launches.
         *
         *     A field submitted unchanged arrives as its masked display value (the UI
         *     shows ``••••••ab12``), which is not a credential and must not be written
         *     over the real one. Those are dropped here rather than in the browser, since
         *     the browser is not where that invariant should live.
         */
        put: operations["put_credentials_api_config_credentials_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmark/{name}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_benchmark__name__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmark/{name}/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pairs
         * @description Pairs to work through.
         *
         *     ``needs_second_pass`` surfaces already-labelled pairs for a *different*
         *     annotator, which is how the >=20% double-annotated overlap gets built.
         */
        get: operations["list_pairs_api_benchmark__name__pairs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmark/{name}/pairs/{pair_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pair */
        get: operations["get_pair_api_benchmark__name__pairs__pair_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmark/{name}/label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Label Pair */
        post: operations["label_pair_api_benchmark__name__label_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmark/{name}/adjudicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjudicate
         * @description Settle a disagreement between two annotators.
         *
         *     The adjudicated label becomes ``final_label``; both original labels are
         *     kept, so kappa still reflects the raw disagreement rather than the
         *     tidied-up version.
         */
        post: operations["adjudicate_api_benchmark__name__adjudicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmark/{name}/disagreements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disagreements */
        get: operations["disagreements_api_benchmark__name__disagreements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjudicateRequest */
        AdjudicateRequest: {
            /** Pair Id */
            pair_id: string;
            adjudicated_label: components["schemas"]["Verdict"];
            /** Adjudicated By */
            adjudicated_by: string;
        };
        /** BatchRef */
        BatchRef: {
            /** Citation Id */
            citation_id: string;
            /** Download Successful */
            download_successful: boolean;
            /**
             * Judgeable
             * @default false
             */
            judgeable: boolean;
            content_quality?: components["schemas"]["ContentQuality"] | null;
            /** Winning Url */
            winning_url?: string | null;
            /** Format */
            format?: string | null;
            /** Resolution Attempts */
            resolution_attempts?: components["schemas"]["ResolutionAttempt"][];
            reference_check?: components["schemas"]["ReferenceCheck"] | null;
            /** Notes */
            notes: string;
            /** Sibling Claim Ids */
            sibling_claim_ids?: string[];
        };
        /** Body_create_run_api_runs_post */
        Body_create_run_api_runs_post: {
            /** Pdf */
            pdf?: string | null;
            /** Pdf Path */
            pdf_path?: string | null;
        };
        /**
         * CitationDetails
         * @description Details about a citation
         */
        CitationDetails: {
            /** Title */
            title?: string | null;
            /** Authors */
            authors?: string[] | null;
            /** Year */
            year?: number | null;
            /** Url */
            url?: string | null;
            /** Doi */
            doi?: string | null;
            /** Raw Text */
            raw_text: string;
        };
        /** CitationRef */
        CitationRef: {
            /** Id */
            id?: string | null;
            /** Marker */
            marker?: string | null;
            /** Raw Text */
            raw_text?: string | null;
            details?: components["schemas"]["CitationDetails"] | null;
        };
        /**
         * ClaimDetail
         * @description ClaimRow plus the extras only the detail drawer (S4) needs.
         */
        ClaimDetail: {
            /** Claim Id */
            claim_id: string;
            /** Text */
            text: string;
            /** Claim Type */
            claim_type: string;
            /**
             * Group
             * @enum {string}
             */
            group: "qual_uncited" | "quant_uncited" | "qual_cited" | "quant_cited";
            /** Is Original */
            is_original: boolean;
            /** Originally Uncited */
            originally_uncited: boolean;
            found_source?: components["schemas"]["FoundDatasetSource"] | null;
            citation?: components["schemas"]["CitationRef"] | null;
            location_in_text?: components["schemas"]["LocationRef"] | null;
            result?: components["schemas"]["ResultRef"] | null;
            batch?: components["schemas"]["BatchRef"] | null;
            /** Generated Script Path */
            generated_script_path?: string | null;
            /** Raw Citation Text */
            raw_citation_text?: string | null;
            /** Generated Script Source */
            generated_script_source?: string | null;
            /** Sibling Claims */
            sibling_claims?: components["schemas"]["ClaimRow"][];
        };
        /** ClaimRow */
        ClaimRow: {
            /** Claim Id */
            claim_id: string;
            /** Text */
            text: string;
            /** Claim Type */
            claim_type: string;
            /**
             * Group
             * @enum {string}
             */
            group: "qual_uncited" | "quant_uncited" | "qual_cited" | "quant_cited";
            /** Is Original */
            is_original: boolean;
            /** Originally Uncited */
            originally_uncited: boolean;
            found_source?: components["schemas"]["FoundDatasetSource"] | null;
            citation?: components["schemas"]["CitationRef"] | null;
            location_in_text?: components["schemas"]["LocationRef"] | null;
            result?: components["schemas"]["ResultRef"] | null;
            batch?: components["schemas"]["BatchRef"] | null;
            /** Generated Script Path */
            generated_script_path?: string | null;
        };
        /** ClaimsPage */
        ClaimsPage: {
            /** Claims */
            claims: components["schemas"]["ClaimRow"][];
            /** Total */
            total: number;
            /** Facets */
            facets?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** CompareResult */
        CompareResult: {
            /** Run A */
            run_a: string;
            /** Run B */
            run_b: string;
            /** Rows */
            rows: components["schemas"]["CompareRow"][];
        };
        /** CompareRow */
        CompareRow: {
            /** Claim Id */
            claim_id: string;
            /** Text */
            text: string;
            a_verdict?: components["schemas"]["Verdict"] | null;
            /** A Confidence */
            a_confidence?: number | null;
            b_verdict?: components["schemas"]["Verdict"] | null;
            /** B Confidence */
            b_confidence?: number | null;
            /**
             * Changed
             * @default false
             */
            changed: boolean;
        };
        /** ConfigStatus */
        ConfigStatus: {
            /** Env Keys */
            env_keys: {
                [key: string]: boolean;
            };
            /** Thresholds */
            thresholds: {
                [key: string]: unknown;
            };
        };
        /**
         * ContentQuality
         * @description How good the fetched source text is as evidence — Tier 0.3.
         *
         *     A successful HTTP fetch is necessary but not sufficient. Publisher landing
         *     pages (abstract + reference list) clear any length floor and then get
         *     RAG-searched for evidence they cannot contain.
         * @enum {string}
         */
        ContentQuality: "full_text" | "abstract_only" | "paywall_interstitial" | "rejected";
        /** CostSummary */
        CostSummary: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Input Cost
             * @default 0
             */
            input_cost: number;
            /**
             * Output Cost
             * @default 0
             */
            output_cost: number;
            /**
             * Total Cost
             * @default 0
             */
            total_cost: number;
        };
        /**
         * CredentialField
         * @description One editable credential, as the config page renders it.
         *
         *     ``value`` is the real value for non-secret fields (an email, a proxy
         *     hostname — a user fixing their own typo needs to see it) and a masked hint
         *     for secrets. A secret's plaintext never leaves the server.
         */
        CredentialField: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Group */
            group: string;
            /** Help */
            help: string;
            /**
             * Impact
             * @default
             */
            impact: string;
            /**
             * Secret
             * @default true
             */
            secret: boolean;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /**
             * Placeholder
             * @default
             */
            placeholder: string;
            /** Signup Url */
            signup_url?: string | null;
            /**
             * Input Type
             * @default text
             */
            input_type: string;
            /**
             * Present
             * @default false
             */
            present: boolean;
            /**
             * Value
             * @default
             */
            value: string;
            /**
             * From Shell
             * @default false
             */
            from_shell: boolean;
        };
        /** CredentialsStatus */
        CredentialsStatus: {
            /** Fields */
            fields: components["schemas"]["CredentialField"][];
            /** Group Order */
            group_order: string[];
            /** Group Blurb */
            group_blurb: {
                [key: string]: string;
            };
            /** Env Path */
            env_path: string;
        };
        /**
         * CredentialsUpdate
         * @description Names are validated against the catalogue server-side; an unknown key is
         *     rejected rather than written, so this endpoint cannot set arbitrary
         *     environment variables.
         */
        CredentialsUpdate: {
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /**
         * EvidenceSpan
         * @description One quoted passage backing a verdict — Tier 0.5.
         *
         *     The whole point is that a human can check the finding in ten seconds:
         *     ``quote`` is verbatim text from the source, ``source_url`` resolves to the
         *     thing that was actually fetched, and ``verified_verbatim`` records whether
         *     ASV confirmed the quote really appears there (LLMs fabricate quotes; see
         *     VALUE_PROPOSITION.md §2.4(c) for this system doing exactly that once).
         */
        EvidenceSpan: {
            /** Quote */
            quote: string;
            /**
             * Role
             * @default supporting
             * @enum {string}
             */
            role: "supporting" | "contradicting" | "nearest_relevant";
            /** Source Url */
            source_url: string;
            /** Retrieval Score */
            retrieval_score?: number | null;
            /** Char Start */
            char_start?: number | null;
            /** Char End */
            char_end?: number | null;
            /** Locator */
            locator?: string | null;
            /**
             * Verified Verbatim
             * @default false
             */
            verified_verbatim: boolean;
        };
        /**
         * FoundDatasetSource
         * @description Dataset source found by sourcefinder for originally uncited claims
         */
        FoundDatasetSource: {
            /** Source Url */
            source_url: string;
            /** Source Type */
            source_type: string;
            /** Relevance Score */
            relevance_score: number;
            /** Found By Claim Id */
            found_by_claim_id: string;
            /**
             * Reused Count
             * @default 0
             */
            reused_count: number;
            /** Search Query */
            search_query?: string | null;
            /** Found At */
            found_at?: string;
        };
        /** FunnelStage */
        FunnelStage: {
            /** Stage */
            stage: string;
            /** Count */
            count: number;
        };
        /** GoldEvidence */
        GoldEvidence: {
            /** Quote */
            quote: string;
            /** Char Start */
            char_start?: number | null;
            /** Char End */
            char_end?: number | null;
        };
        /**
         * GoldPair
         * @description One hand-labelled claim-source pair.
         */
        GoldPair: {
            /** Pair Id */
            pair_id: string;
            /** Field */
            field: string;
            /** Provenance */
            provenance: string;
            /** Claim Text */
            claim_text: string;
            /** Claim Id */
            claim_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            source?: components["schemas"]["GoldSource"];
            label: components["schemas"]["Verdict"];
            /**
             * Label Reason
             * @default
             */
            label_reason: string;
            /** Evidence Spans */
            evidence_spans?: components["schemas"]["GoldEvidence"][];
            /** Miscitation Types */
            miscitation_types?: string[];
            /**
             * Difficulty
             * @default easy
             */
            difficulty: string;
            /**
             * Is Seeded Negative
             * @default false
             */
            is_seeded_negative: boolean;
            /** Derived From */
            derived_from?: string | null;
            /** Annotator */
            annotator?: string | null;
            /** Annotated At */
            annotated_at?: string | null;
            /** Second Annotator */
            second_annotator?: string | null;
            second_label?: components["schemas"]["Verdict"] | null;
            /** Adjudicated By */
            adjudicated_by?: string | null;
            adjudicated_label?: components["schemas"]["Verdict"] | null;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** GoldSource */
        GoldSource: {
            /** Doi */
            doi?: string | null;
            /** Url */
            url?: string | null;
            /** Title */
            title?: string | null;
            /** Content Quality */
            content_quality?: string | null;
            /** Text Sha256 */
            text_sha256?: string | null;
            /**
             * Snapshot Kind
             * @default excerpt
             */
            snapshot_kind: string;
            /**
             * Open Access
             * @default false
             */
            open_access: boolean;
        };
        /** GoldStats */
        GoldStats: {
            /** Composition */
            composition: {
                [key: string]: unknown;
            };
            /** Readiness Problems */
            readiness_problems: string[];
            /** Miscitation Types */
            miscitation_types: {
                [key: string]: string;
            };
            /** Labelled */
            labelled: number;
            /** Unlabelled */
            unlabelled: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HighlightQuad */
        HighlightQuad: {
            /** Claim Id */
            claim_id: string;
            /** Page */
            page: number;
            /** Quads */
            quads: number[][];
        };
        /** LabelRequest */
        LabelRequest: {
            /** Pair Id */
            pair_id: string;
            label: components["schemas"]["Verdict"];
            /** Annotator */
            annotator: string;
            /**
             * Label Reason
             * @default
             */
            label_reason: string;
            /** Evidence Spans */
            evidence_spans?: components["schemas"]["GoldEvidence"][];
            /** Miscitation Types */
            miscitation_types?: string[];
            /**
             * Difficulty
             * @default easy
             */
            difficulty: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Second Pass
             * @default false
             */
            second_pass: boolean;
        };
        /** LocationRef */
        LocationRef: {
            /** Start */
            start?: number | null;
            /** End */
            end?: number | null;
            /** Chunk Id */
            chunk_id?: number | null;
        };
        /**
         * NotCheckableReason
         * @description Why ASV declined to judge a claim.
         *
         *     The reason is what tells a user what to *do*: ``abstract_only`` means "find
         *     the full text", ``reference_not_found`` means "check your bibliography",
         *     ``source_download_failed`` means "try again or log in". Collapsing these into
         *     one ``failed`` is the defect Tier 0.2 exists to fix.
         * @enum {string}
         */
        NotCheckableReason: "no_source_available" | "original_contribution" | "source_not_resolved" | "source_download_failed" | "abstract_only" | "paywall_interstitial" | "content_rejected" | "retrieval_empty" | "evidence_unverifiable" | "reference_not_found" | "reference_unverified" | "unresolvable_by_design" | "validation_error";
        /**
         * ReferenceAudit
         * @description Tier 0.6 bibliography-audit rollup for one run.
         */
        ReferenceAudit: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Verified
             * @default 0
             */
            verified: number;
            /**
             * Ambiguous
             * @default 0
             */
            ambiguous: number;
            /**
             * Not Found In Indexes
             * @default 0
             */
            not_found_in_indexes: number;
            /**
             * Unindexed By Design
             * @default 0
             */
            unindexed_by_design: number;
            /**
             * Unverified
             * @default 0
             */
            unverified: number;
            /**
             * Retracted
             * @default 0
             */
            retracted: number;
            /**
             * Concern Raised
             * @default 0
             */
            concern_raised: number;
        };
        /**
         * ReferenceCheck
         * @description Does the cited reference exist in the scholarly record? — Tier 0.6.
         *
         *     Orthogonal to the claim verdict: a reference that cannot be found says
         *     nothing about whether the claim is true, and a retracted source can still
         *     contain the sentence being cited. Both surface as their own object plus
         *     ``ValidationResult.flags`` rather than as verdicts.
         *
         *     ``indexes_queried`` vs ``indexes_responded`` is the whole of the
         *     "an API outage must never read as an accusation" rule: a
         *     ``NOT_FOUND_IN_INDEXES`` status requires at least two indexes to have
         *     actually responded.
         */
        ReferenceCheck: {
            /** Citation Id */
            citation_id: string;
            /** Raw Citation Text */
            raw_citation_text: string;
            /** Parsed */
            parsed?: {
                [key: string]: unknown;
            };
            status: components["schemas"]["ReferenceStatus"];
            /** Matched Doi */
            matched_doi?: string | null;
            /** Matched Title */
            matched_title?: string | null;
            /** Matched Url */
            matched_url?: string | null;
            /** Match Score */
            match_score?: number | null;
            /** Near Miss */
            near_miss?: {
                [key: string]: unknown;
            } | null;
            /** Indexes Queried */
            indexes_queried?: string[];
            /** Indexes Responded */
            indexes_responded?: string[];
            /** @default unknown */
            retraction_status: components["schemas"]["RetractionStatus"];
            /** Retraction Notice Url */
            retraction_notice_url?: string | null;
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /** Checked At */
            checked_at?: string;
        };
        /**
         * ReferenceCheckRow
         * @description A bibliography-audit row, plus how many claims depend on it.
         */
        ReferenceCheckRow: {
            /** Citation Id */
            citation_id: string;
            /** Raw Citation Text */
            raw_citation_text: string;
            /** Parsed */
            parsed?: {
                [key: string]: unknown;
            };
            status: components["schemas"]["ReferenceStatus"];
            /** Matched Doi */
            matched_doi?: string | null;
            /** Matched Title */
            matched_title?: string | null;
            /** Matched Url */
            matched_url?: string | null;
            /** Match Score */
            match_score?: number | null;
            /** Near Miss */
            near_miss?: {
                [key: string]: unknown;
            } | null;
            /** Indexes Queried */
            indexes_queried?: string[];
            /** Indexes Responded */
            indexes_responded?: string[];
            /** @default unknown */
            retraction_status: components["schemas"]["RetractionStatus"];
            /** Retraction Notice Url */
            retraction_notice_url?: string | null;
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /** Checked At */
            checked_at?: string;
            /**
             * Num Claims
             * @default 0
             */
            num_claims: number;
        };
        /**
         * ReferenceStatus
         * @description Whether the cited reference exists in the scholarly record — Tier 0.6.
         *
         *     ``NOT_FOUND_IN_INDEXES`` is deliberately *not* named "fabricated". Saying a
         *     real reference does not exist is an allegation; the enum, the explanation
         *     strings, and the UI all say only what was actually observed — that the
         *     named indexes did not return a match.
         * @enum {string}
         */
        ReferenceStatus: "verified" | "ambiguous" | "not_found_in_indexes" | "unindexed_by_design" | "unverified";
        /**
         * ResolutionAttempt
         * @description One URL try when resolving a citation to a downloadable source.
         */
        ResolutionAttempt: {
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Downloaded */
            downloaded: boolean;
            content_quality?: components["schemas"]["ContentQuality"] | null;
            /** Error */
            error?: string | null;
        };
        /** ResultRef */
        ResultRef: {
            verdict: components["schemas"]["Verdict"];
            not_checkable_reason?: components["schemas"]["NotCheckableReason"] | null;
            /** Passed */
            passed: boolean;
            /** Confidence */
            confidence?: number | null;
            /** Method */
            method: string;
            /** Explanation */
            explanation: string;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceSpan"][];
            /** Source Url */
            source_url?: string | null;
            content_quality?: components["schemas"]["ContentQuality"] | null;
            /** Flags */
            flags?: string[];
            /** Errors */
            errors?: string | null;
            /** Sources Used */
            sources_used?: string[];
            /** Validated At */
            validated_at?: string | null;
            /** Validation Metadata */
            validation_metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Legacy
             * @default false
             */
            legacy: boolean;
        };
        /**
         * RetractionStatus
         * @description Retraction / correction state of a cited source — Tier 0.6.
         *
         *     Orthogonal to the claim verdict: a retracted paper can still literally
         *     contain the sentence being cited, so this raises a flag rather than
         *     changing a verdict.
         * @enum {string}
         */
        RetractionStatus: "none" | "retracted" | "concern_raised" | "corrected" | "unknown";
        /** RetryRequest */
        RetryRequest: {
            /** Override Url */
            override_url?: string | null;
        };
        /** RetryResponse */
        RetryResponse: {
            /** Citation Id */
            citation_id: string;
            /** Download Successful */
            download_successful: boolean;
            /** Num Claims */
            num_claims: number;
            /** Job Id */
            job_id: string;
        };
        /** RunCreateResponse */
        RunCreateResponse: {
            /** Run Id */
            run_id: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Run Id */
            run_id: string;
            /** Pdf Stem */
            pdf_stem: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "awaiting_login" | "complete" | "failed";
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Total Elapsed Seconds */
            total_elapsed_seconds?: number | null;
            cost?: components["schemas"]["CostSummary"] | null;
            /** Steps */
            steps?: {
                [key: string]: components["schemas"]["StepStats"];
            };
            /** Verdict Breakdown */
            verdict_breakdown?: components["schemas"]["VerdictBreakdown"][];
            /** Not Checkable Reasons */
            not_checkable_reasons?: {
                [key: string]: number;
            };
            /** Resolution Funnel */
            resolution_funnel?: components["schemas"]["FunnelStage"][];
            reference_audit?: components["schemas"]["ReferenceAudit"] | null;
            /** Awaiting Login Domains */
            awaiting_login_domains?: string[];
        };
        /** RunSummaryRow */
        RunSummaryRow: {
            /** Run Id */
            run_id: string;
            /** Pdf Stem */
            pdf_stem: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "awaiting_login" | "complete" | "failed";
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Total Claims */
            total_claims?: number | null;
            /** Substantiated */
            substantiated?: number | null;
            /** Partially Substantiated */
            partially_substantiated?: number | null;
            /** Not Substantiated */
            not_substantiated?: number | null;
            /** Contradicted */
            contradicted?: number | null;
            /** Not Checkable */
            not_checkable?: number | null;
            /** Checkable Rate */
            checkable_rate?: number | null;
            /** Substantiation Rate */
            substantiation_rate?: number | null;
            /** Evidence Backed Verdicts */
            evidence_backed_verdicts?: number | null;
            reference_audit?: components["schemas"]["ReferenceAudit"] | null;
            /** Total Elapsed Seconds */
            total_elapsed_seconds?: number | null;
            cost?: components["schemas"]["CostSummary"] | null;
            /** Awaiting Login Domains */
            awaiting_login_domains?: string[];
        };
        /** SourceRow */
        SourceRow: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "dataset" | "text";
            /** Citation Id */
            citation_id: string;
            /** Citation Text */
            citation_text?: string | null;
            /** Raw Citation Text */
            raw_citation_text?: string | null;
            citation_details?: components["schemas"]["CitationDetails"] | null;
            /** Resolution Attempts */
            resolution_attempts?: components["schemas"]["ResolutionAttempt"][];
            /** Winning Url */
            winning_url?: string | null;
            /** Format */
            format?: string | null;
            /** Filename */
            filename?: string | null;
            /** Downloaded At */
            downloaded_at?: string | null;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Batch Num Claims
             * @default 0
             */
            batch_num_claims: number;
            /**
             * Batch Download Successful
             * @default false
             */
            batch_download_successful: boolean;
            /**
             * Batch Judgeable
             * @default false
             */
            batch_judgeable: boolean;
            content_quality?: components["schemas"]["ContentQuality"] | null;
        };
        /** StepStats */
        StepStats: {
            /** Elapsed Seconds */
            elapsed_seconds?: number | null;
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Checkable
             * @default 0
             */
            checkable: number;
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Avg Confidence */
            avg_confidence?: number | null;
            /** Verdicts */
            verdicts?: {
                [key: string]: number;
            };
            /** Not Checkable Reasons */
            not_checkable_reasons?: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @description What ASV concluded about one claim.
         *
         *     Exactly one of these lands on every ``ValidationResult``. The four
         *     non-abstention values are *judgments about the claim* and, per Tier 0.5,
         *     may only be emitted with a verbatim-verified evidence span plus a
         *     resolvable source URL. ``NOT_CHECKABLE`` is an abstention and carries a
         *     ``NotCheckableReason`` instead of a confidence.
         * @enum {string}
         */
        Verdict: "substantiated" | "partially_substantiated" | "not_substantiated" | "contradicted" | "not_checkable";
        /** VerdictBreakdown */
        VerdictBreakdown: {
            /**
             * Group
             * @enum {string}
             */
            group: "qual_uncited" | "quant_uncited" | "qual_cited" | "quant_cited";
            /**
             * Substantiated
             * @default 0
             */
            substantiated: number;
            /**
             * Partially Substantiated
             * @default 0
             */
            partially_substantiated: number;
            /**
             * Not Substantiated
             * @default 0
             */
            not_substantiated: number;
            /**
             * Contradicted
             * @default 0
             */
            contradicted: number;
            /**
             * Not Checkable
             * @default 0
             */
            not_checkable: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryRow"][];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_run_api_runs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pdfs_api_pdfs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_references_api_runs__run_id__references_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceCheckRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_complete_api_runs__run_id__login_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_runs_api_compare_get: {
        parameters: {
            query: {
                a: string;
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_claims_api_runs__run_id__claims_get: {
        parameters: {
            query?: {
                group?: string | null;
                verdict?: string | null;
                not_checkable_reason?: string | null;
                flag?: string | null;
                claim_type?: string | null;
                method?: string | null;
                has_evidence?: boolean | null;
                citation_id?: string | null;
                is_original?: boolean | null;
                originally_uncited?: boolean | null;
                min_confidence?: number | null;
                max_confidence?: number | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_claim_api_runs__run_id__claims__claim_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_runs__run_id__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_citation_api_runs__run_id__sources__citation_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                citation_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_pdf_api_runs__run_id__paper_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_highlights_api_runs__run_id__highlights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighlightQuad"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigStatus"];
                };
            };
        };
    };
    get_credentials_api_config_credentials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialsStatus"];
                };
            };
        };
    };
    put_credentials_api_config_credentials_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialsStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_benchmark__name__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pairs_api_benchmark__name__pairs_get: {
        parameters: {
            query?: {
                unlabelled_only?: boolean;
                needs_second_pass?: boolean;
                limit?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldPair"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pair_api_benchmark__name__pairs__pair_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pair_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    label_pair_api_benchmark__name__label_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjudicate_api_benchmark__name__adjudicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjudicateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disagreements_api_benchmark__name__disagreements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldPair"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
